### ISSUE TITLE
Organização de diretórios

### ISSUE THREAD

**Issue by marianaalucena** [Izaquielnn/dev-web#5]
Creio que seja uma boa prática manter os arquivos com extensão .js e .css de uma mesma funcionalidade dentro de uma só pasta, tanto para componentes quanto para páginas. Dessa forma, será mais fácil de administrar quando tiveres mais funcionalidades. 
Por exemplo: 

![image](https://user-images.githubusercontent.com/20727725/153772223-7b7bef1c-3b57-45fe-93b2-66c135d77684.png)

Eu criaria a pasta Feed e Post e colocaria os arquivos referentes a cada página dentro delas.

**Comment by Izaquielnn** [comment]
Feito! Obrigado pela dica :)
