### ISSUE TITLE
Fazer o uso de useContext na aplicação

### ISSUE THREAD

**Issue by mathsantana** [Izaquielnn/dev-web#7]
Fazer o uso de contexto para estados globais, ou seja, que vários componentes precisem consumir/alterar, como, por exemplo, estados referentes ao tema da aplicação, ao usuário logado, etc.

**Comment by DiegoGamaV** [comment]
A ideia de usar useContext para usuários logados é bem interessante, porque aí você pode utilizar esse estado quando o usuário for criar uma nova postagem ou editá-la (para enviar informações relevantes para rotas que precisam de autenticação do usuário logado)
